name: ci

on:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          load: true # This allows you to load the built image into Docker's local image store
          context: .
          target: test
          tags: whiscy:test

      - name: Run unit tests
        run: >
          docker run
          -v ${PWD}/coverage-report:/opt/software/whiscy/coverage-report
          --rm
          whiscy:test
          pytest -m unit --cov --cov-report xml:/opt/software/whiscy/coverage-report/coverage.xml --cov-append -vv --hypothesis-show-statistics

  regression-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load Docker image
        run: docker load -i whiscy.tar

      - name: Run regression tests
        run: >
          docker run
          -v ${PWD}/coverage-report:/opt/software/whiscy/coverage-report
          --rm
          whiscy:test
          pytest -m regression --cov --cov-report xml:/opt/software/whiscy/coverage-report/coverage.xml --cov-append -vv --hypothesis-show-statistics
